### PR TITLE
eventQueue uses LinkedList for better performance

### PR DESCRIPTION
**Pull request by miqt**

### CODE REVIEW

**Comment by tdtran** [comment]
You need to quantify the potential perf gains. In my experience ArrayList is good in almost all situations and is a good default choice unless **proved otherwise**

**Comment by miqt** [comment]
> You need to quantify the potential perf gains. In my experience ArrayList is good in almost all situations and is a good default choice unless **proved otherwise**

ArrayList Is an array structure,This `remove(index)` and `add(index,E)` method Time complexity is O(n).
LinkedList Is an link structure,This `remove(index)` and `add(index,E)` method Time complexity is O(1).

The 'eventQueue' only uses the 'add' and 'remove' methods, so changing to a LinkedList here is a better choice.

**Comment by tdtran** [comment]
`eventQueue` only adds new element at the very end of the list. That's O(1). It calls `remove(0)` which requires moving all the remaining array's element one position to the beginning of the array. That's indeed O(n) but that memcopy is done in native code. LinkedList's add allocates memory for every new element. The memory consumption is about 3x compared to LinkedList. It also means time for GC. Maybe costs more than the memcopy op needed by ArrayList, depending on how good is the GC code. So for me it's not clear cut.  Can you make some measurements and give us real numbers, in nanoseconds / milliseconds? That would be helpful.

**Comment by miqt** [comment]
Thanks, what you said makes sense. I experimented with the test code. The result is really not very different, and I think the length of the eventQueue is usually =1, which depends on the logic of the post method.... :-)

**Pull request closed without merging**
