### PR TITLE
EventBus class add setDefault method

### PR DESCRIPTION
**Pull request by getActivity**
Hello, I use the EventBus Apt plug-ins, but involve changes to the code is very much, very easy to appear omissions, I myself have done many frameworks, I object to this kind of practice, because I can't make good use of it, it does not conform to the open closed principle Java design patterns, I recommend to extend EventBus method, because in many cases, we only need a singleton EventBus instance, to the EventBus class maintenance, inherit the EventBus items and replace the original code cost is very high,I recommend solving this problem this way, thank you

### CODE REVIEW

**Comment by getActivity** [comment]
`EventBus.setDefault(EventBus.builder().addIndex(new MyEventBusIndex()).build());`

**Comment by greenrobot-team** [comment]
Why does `EventBus.builder().installDefaultEventBus();` not work for you?
http://greenrobot.org/eventbus/documentation/configuration/

-Uwe

**Comment by getActivity** [comment]
yes，`EventBus.builder().installDefaultEventBus()`  and `EventBus.getDefault()` It works the same way

**Comment by getActivity** [comment]
Because I want to add a SubscriberInfoIndex without creating a new EventBus instance

**Comment by getActivity** [comment]
Sorry, I didn't read the source code carefully

        EventBus.builder()
                .ignoreGeneratedIndex(false)
                .addIndex(new MyEventBusIndex())
                .installDefaultEventBus();

**Pull request closed without merging**
