### PR TITLE
Support for plain old Java

### PR DESCRIPTION
**Pull request by william-ferguson-au**
Rebased off annotations branch.
Replacement for PR #174 

NB I can't get the annotations branch to build using IntelliJ.
Not sure if the Gradle config in the branch has changed or my INtelliJ Gradle config has somehow lost its flavour (this is the only project I touch that uses Gradle).

### CODE REVIEW

**Comment by patton73** [comment]
Any news about plain java support? Are you planning to release soon a polished version of the bus
removing android dependecies?
Thank you in advance.
Andrea.

**Comment by william-ferguson-au** [comment]
I'd love to see it too @greenrobot :-)

**Comment by william-ferguson-au** [comment]
Hey Markus, any chance of getting the plain-java branch merged?
I'm still using a branch of 2.4.1 at the moment.

**Comment by patton73** [comment]
Anyway the branch does not compile with only plain-java. It still requires android dependencies.
It is possible to have the logsystem injected from outside so that it won't be anymore a dependency for the eventbus? 
Thanks.

Andrea.

**Comment by william-ferguson-au** [comment]
It doesn't matter whether the branch requires Android deps to compile. What matters is that is can execute without those deps at runtime.

Part of my original PR did wrapper the logging system so that either the Android or another could be injected.

**Comment by acatinon** [comment]
Any update about the plain-java branch ?

**Comment by Nath5** [comment]
I would also like to know if there are any updates?

**Comment by Kixxy** [comment]
I would like to see this implemented. I see greenrobot has recent activity but this has not been moving very fast.

**Comment by william-ferguson-au** [comment]
+1 I submitted the original patch for this 18 months ago and it has yet to see the light of day.

Am at the point of forking the EventBus to 

1.  add this, 
2.  simplify the delivery mechanism ala #308 
3. ditch the org.greenrobot.eventbus.util*Dialog* classes as they don't belong in EventBus.

**Comment by Kixxy** [comment]
@william-ferguson-au can you do this soon? I am working on a project and if I don't get something like this soon (for plain java) I will end up writing my own implementation.

**Comment by patton73** [comment]
@william-ferguson-au I second that. Just tell us where you will open new git project and when. This is really needed. I would also add support for logback or similar so that we can have a fully standard plain java code.
Andrea.

**Comment by Kixxy** [comment]
I made a version of this from scratch with Java 8+ support on plain jdk. It's integrated into the program I am using but if anyone is interested I can open source it as another project. It currently supports generics (as events, so EventFoo<BlahBlah>), annotations, canceling, and priority.

**Comment by shaigem** [comment]
@Kixxy I've been waiting for EventBus to support plain java. If you release your version I'll definitely take a look at it

**Comment by Kixxy** [comment]
I uploaded my version of Eventbus. please note i just started it a few days ago and have no guarentees anything works right. feel free to look at the code, pull request, critique etc. https://github.com/Kixxy/EventBus

**Comment by patton73** [comment]
Any chances in about to see the new plain java version?
@william-ferguson-au did you fork the code?

Thanks.

**Comment by william-ferguson-au** [comment]
No. It's on my perennial todo list.

**Comment by patton73** [comment]
I try my last call :)
Is there any chance to see a java plain version of the bus? Is there someone at least who forked the bus to free it from android dependencies?

**Comment by william-ferguson-au** [comment]
I continue to use a fork of 2.4.1 to which I originally applied this change.
In order to make it work, you only need to apply the changes in this commit https://github.com/greenrobot/EventBus/pull/247/commits/1558ebf894dc9d8cac5db8b0676cfcd2c259418a

Can I suggest that you do so and raise a new PR from a clean EventBus trunk.
We might have more luck getting it integrated.

**Comment by patton73** [comment]
Ehm if i recall correctly i should have a version that starts from laster master at which i applied your patch and fixed the things that did not compile. I can do the fork but actually i am not sure to have time to work on it. Dunno if there are people who are interested in mantaining the new fork. Shoult we try to make a little community for this project?

**Comment by william-ferguson-au** [comment]
Options
1) You to fork and apply this patch, I'll help you to maintain it.
2) Give the Green Robot guys the PR again in a more consumable format (this PR is based on too old a branch now).

My preference is the latter, but it's up to them whether they take the PR or not. But if they don't (within X weeks) then you can apply the PR to your fork and we go option 1.

**Comment by patton73** [comment]
Hi William,

I applied your patch on the lastest master.
All OK but the file org.greenrobot.eventbus.util.AsyncExecutor.java that is completely different and your patch does not apply. Can you have a look at it so that i can finalize the revision and make the new PR?
Thanks.

**Comment by william-ferguson-au** [comment]
@patton73 there were no conflicts. I have submitted a fresh PR from that commit https://github.com/greenrobot/EventBus/pull/467.
If Markus doesn't merge that PR then I will publish my fork. But I warn you. If I publish a fork of this project I will take a blowtorch to it and fix up the things that I have always have a beef with. This may not be to your liking, so you might want to consider your own fork in that scenario.

**Comment by william-ferguson-au** [comment]
Closing this PR in favour of https://github.com/greenrobot/EventBus/pull/467

**Pull request closed without merging**
