### PR TITLE
Decoupled Android EventBus from Core EventBus. Removed the need to Jetify this library.

### PR DESCRIPTION
**Pull request by andob**
- Removed Android dependencies from the core EventBus altogether. Thus, the core library can be used in plain java.
- Made another module to support Android projects. Decoupled Android-related functionalities (logging, main thread support) into this module.
- Removed error dialog classes.
- This would remove the need to use Jetifier in our Android projects. Core eventbus doesn't depend on anything, eventbus-android module depends only on Android SDK. No need to use support libraries or AndroidX, thus no need to Jetify

Java users will import the library with:

```
implementation 'org.greenrobot:eventbus:<version>'
```

Android users will import the library with:
```
implementation 'org.greenrobot:eventbus:<version>'
implementation 'org.greenrobot:eventbus-android:<version>'
annotationProcessor 'org.greenrobot:eventbus-processor:<version>'
```

If android users will import the library forgetting to also import android compatibility module:
```
implementation 'org.greenrobot:eventbus:<version>'
annotationProcessor 'org.greenrobot:eventbus-processor:<version>'
```

A runtime exception will be thown at ``eventBus.register(this)``: ``Looks like you are using the latest version of EventBus on Android...``, crashing the application. This will help users when they update the library, notifying them of the breaking change.

### CODE REVIEW

**Comment by greenrobot-team** [comment]
This is actually a great idea to work off, thanks for this!

@greenrobot Thoughts?

**Comment by andob** [comment]
> would make sense to name the base library eventbus-java and use the existing eventbus name for the Android only library

@greenrobot-team Do you need me to do something on my side regarding this, or you will do this change after the review / merge?

Also I think naming can be configured when publishing maven artifacts, no need to rename the modules.
We can use current module / directory names, and publish them with different names:
/EventBus -> org.greenrobot:eventbus-java
/eventbus-android -> org.greenrobot:eventbus

**Comment by greenrobot-team** [comment]
There is nothing for you to do, thanks again for the suggestion!

**Comment by greenrobot-team** [comment]
Closed in favor of #670.

**Pull request closed without merging**
