### PR TITLE
Stops NoClassDefFound exceptions on EventBus#register(Object)

### LINKED ISSUE #149: Fatal Exception: java.lang.NoClassDefFoundError android/telephony/CellInfoGsm
Hi,
On specific mobiles eventbus crashes with following error. 

 Fatal Exception: java.lang.NoClassDefFoundError
android/telephony/CellInfoGsm
de.greenrobot.event.SubscriberMethodFinder.findSubscriberMethods
Caused by java.lang.ClassNotFoundException
	
dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:61)
	
java.lang.Class.getDeclaredMethods (Class.java:703)
	
de.greenrobot.event.SubscriberMethodFinder.findSubscriberMethods (SubscriberMethodFinder.java:75)
	
de.greenrobot.event.EventBus.register (EventBus.java:163)
	
de.greenrobot.event.EventBus.registerSticky (EventBus.java:151)

Looks like findSubscriberMethods is trying to access methods which are marked as @TargetApi(17) while the phone is using api 16. Hence eventbus is not able to find those classes which are not available in api 16. Looks like a bug. Is there any workaround?

### PR DESCRIPTION
**Pull request by yuzeh**
Should Fix #149, #151, #156

### CODE REVIEW

**Comment by yuzeh** [comment]
@greenrobot Any tips on how to get the project to work with Android Studio/Intellij?

**Comment by yuzeh** [comment]
@greenrobot wondering if there was any movement on this. Thanks!

**Comment by nikclayton** [comment]
Should also fix #139.

**Comment by yuzeh** [comment]
Any update on this? @greenrobot ?

**Pull request closed without merging**
