### PR TITLE
Changed library to use annotations

### PR DESCRIPTION
**Pull request by rjbrock**
The library now requires the use of annotations in order for a method to be subscribed to an event.

``@Subscribe``
``public void mySubscribingMethod(MyEvent event)``

### CODE REVIEW

**Comment by rjbrock** [comment]
@greenrobot Any updates?

**Comment by rjbrock** [comment]
@greenrobot do you know when you will have a chance to take a deeper look?  I am hoping to use this library in our application, but I am holding out until annotations are a part

**Comment by jromero** [comment]
@greenrobot We are also waiting for this feature...

**Comment by andreas-** [comment]
+1

**Comment by rjbrock** [comment]
Thanks!

**Pull request merged**
