### PR TITLE
Support plain java

### PR DESCRIPTION
**Pull request by william-ferguson-au**
PR for issue #173 

NB I didn't add EBLog support into any of the ErrorDialog classes because ErrorDialogManager allows arbitrary log TAG and those classes don't naturally seem to fit into the EventBus library.

### CODE REVIEW

**Comment by william-ferguson-au** [comment]
NB one difference between Sun's implementation of Java security and Android's looks like it has cropped up.

In Android I have been using the pattern:

    class someClass {
        private final Object eventListener = new Object() {
            public void onEvent(SomeEvent e) {
                // react to event
            }
        };

        public void onCreate() {
            EventBus.getDefault().register(eventListener);
        }

        public void onDestroy() {
            EventBus.getDefault().unregister(eventListener);
        }
    }

And this has worked really well.

But the same pattern using Sun's JVM will result in an IllegalAccessException unless I make the eventListener attribute public.

**Comment by william-ferguson-au** [comment]
Scrap that comment about the difference in security.
Looks like I had some stale classes in my test environment.

**Comment by william-ferguson-au** [comment]
Revisiting this again. 
Definitely the case that the Oracle JVM won't allow access to a private eventListener attribute..
Not a big deal, just something to note.

Any chance of integrating this PR soon?

**Comment by Chumper** [comment]
:+1: the only show stopper for me is the need for android. I want to use the event bus in libgdx and plain java version would be awesome.

**Comment by william-ferguson-au** [comment]
Fine by me. I'll run off a branch until then.
Are you going to IO?

If so, I'd love to buy you a beer as way of saying thanks for the library.

**Comment by william-ferguson-au** [comment]
An update on the Sun/Oracle JVM accessibility. It appears that it is is denying access because it is an anonymous class. If I declare a class and then instantiate it its ok.

@greenrobot And great to catch up with you at IO.

**Comment by william-ferguson-au** [comment]
Hey Marcus, any chance of getting this merged?

**Comment by william-ferguson-au** [comment]
Marcus, If you need me to rebase I can.

**Comment by william-ferguson-au** [comment]
Closed in favour of #247

**Pull request closed without merging**
